### ISSUE TITLE
Add PlantUML

### ISSUE THREAD

**Issue by joelparkerhenderson** [Schachte/Mermrender#5]
Great work! Would you be interested in adding capabilities for PlantUML? The syntax is very similar. If so, I'll donate $50 to you or your favorite charity.

Demo diagrams with syntax examples -- see the final one for an example document that I want to render for my team's devops pipeline:

https://github.com/joelparkerhenderson/demo_plantuml/

**Comment by Schachte** [comment]
Looking into this now :)

**Comment by Schachte** [comment]
PR is up @joelparkerhenderson

**Comment by Schachte** [comment]
Going to iterate on this feature as I shift from local disk to blob storage in Azure or S3 in AWS. Don't think it currently supports customizations like fontawesome or monochrome. Baseline generation is working well though.
